// The face registry, checked against engine.py's own answers.
//
// `FaceRegistry.swift` ports the half of face recognition that is not a model,
// and every part of it has a failure mode that still looks plausible: a
// representative picked as "the first hash" instead of "the first hash with a
// thumbnail" (a row that draws nothing), a matcher that reads a pruned hash as a
// zero vector (a person who silently stops matching), a similar-faces ranking
// that forgets to exclude the person's own faces (the same five squares over and
// over), a "merge" that replaces (the user's earlier work disappears), a name
// lookup that is case-SENSITIVE (two "quincy"s).
//
// So this replays a fixture generated by calling the real `engine.face_people`,
// `engine._face_matches`, `engine.similar_faces`, `engine.forget_person`,
// `engine.set_representative`, `engine.name_cluster` and
// `engine.face_clusters` against a cache tree the generator wrote
// (docs/coreml-spike/face_registry_parity.py), and demands identical answers.
//
// Two places the port deliberately differs from the engine are PINNED here
// rather than hidden — `name_cluster` is the one face command in the engine that
// keys its name verbatim, and the one that can store the same hash twice. Both
// are bugs by the engine's own standards (its other five face commands
// case-fold), and the fixture records what the engine did so the difference is a
// decision on the record rather than a silent divergence.
//
// Run: Tests/run_face_registry.sh

@testable import FVPModel
import Foundation

@main
struct FaceRegistryTest {
    static func main() async throws {
        var failures = 0
        func check(_ name: String, _ cond: Bool) {
            print(cond ? "ok   \(name)" : "FAIL \(name)")
            if !cond { failures += 1 }
        }
        func checkEqual<T: Equatable>(_ name: String, _ got: T, _ want: T) {
            let ok = got == want
            print(ok ? "ok   \(name)" : "FAIL \(name) — got \(got), want \(want)")
            if !ok { failures += 1 }
        }
        func checkClose(_ name: String, _ got: Double, _ want: Double, _ tol: Double) {
            let ok = abs(got - want) <= tol
            print(ok ? "ok   \(name)" : "FAIL \(name) — got \(got), want \(want)")
            if !ok { failures += 1 }
        }

        let args = CommandLine.arguments
        let path = args.count > 1
            ? args[1]
            : NSHomeDirectory() + "/fvp-coreml-models/face_registry_fixture.json"
        guard let raw = FileManager.default.contents(atPath: path),
              let root = (try? JSONSerialization.jsonObject(with: raw)) as? [String: Any],
              let cache = root["cache"] as? [String: String],
              let baseRegistry = root["base_registry"] as? [String: [String]],
              let thumbs = root["thumbs"] as? [String],
              let people = root["people"] as? [[String: Any]],
              let similar = root["similar"] as? [[String: Any]],
              let matches = root["matches"] as? [[String: Any]],
              let forget = root["forget"] as? [[String: Any]],
              let representative = root["representative"] as? [[String: Any]],
              let bind = root["bind"] as? [[String: Any]],
              let clusters = root["clusters"] as? [String: Any] else {
            print("SKIP face registry — no fixture at \(path)")
            print("     build it with: /opt/anaconda3/bin/python3 "
                  + "docs/coreml-spike/face_registry_parity.py")
            exit(0)
        }

        func f32(_ b64: String) -> [Float] {
            guard let data = Data(base64Encoded: b64) else { return [] }
            var out = [Float](repeating: 0, count: data.count / 4)
            _ = out.withUnsafeMutableBytes { data.copyBytes(to: $0) }
            return out
        }
        func doubles(_ any: Any?) -> [String: Double] {
            guard let raw = any as? [String: NSNumber] else { return [:] }
            return raw.mapValues { $0.doubleValue }
        }
        func strings(_ any: Any?) -> [String] { (any as? [String]) ?? [] }
        func registryOf(_ any: Any?) -> [String: [String]] {
            (any as? [String: [String]]) ?? [:]
        }

        // --- a scratch tree, written exactly as the generator wrote its own --
        //
        // A thumbnail is only ever tested for existence, so the bytes are the
        // same 4-byte stub the generator used. The vectors are the real fixture
        // vectors: every answer below is a function of them.
        let scratch = NSTemporaryDirectory() + "fvp-face-registry-\(UUID().uuidString)"
        let profile = "quincy"
        defer { try? FileManager.default.removeItem(atPath: scratch) }
        let fm = FileManager.default
        let facesDir = (scratch as NSString).appendingPathComponent("faces")
        // The bundle the app looks in. Built with the same helper `Paths` uses,
        // so this fixture cannot drift from the layout the app reads — which it
        // just did, silently, when the registry moved into the profile's bundle.
        let profileDir = ProfileBundle.dir(profile, root: scratch)

        func writeTree(registry: [String: [String]]) throws {
            try? fm.removeItem(atPath: scratch)
            try fm.createDirectory(atPath: profileDir, withIntermediateDirectories: true)
            for (hash, vector) in cache {
                let sub = (facesDir as NSString).appendingPathComponent(String(hash.prefix(2)))
                try fm.createDirectory(atPath: sub, withIntermediateDirectories: true)
                let data = f32(vector).withUnsafeBufferPointer { Data(buffer: $0) }
                try data.write(to: URL(fileURLWithPath:
                    (sub as NSString).appendingPathComponent(hash + ".f32")))
            }
            for hash in thumbs {
                let sub = (facesDir as NSString).appendingPathComponent(String(hash.prefix(2)))
                try fm.createDirectory(atPath: sub, withIntermediateDirectories: true)
                try Data([0xff, 0xd8, 0xff, 0xd9]).write(to: URL(fileURLWithPath:
                    (sub as NSString).appendingPathComponent(hash + ".jpg")))
            }
            let file = (profileDir as NSString).appendingPathComponent("faces.json")
            try JSONSerialization.data(withJSONObject: registry)
                .write(to: URL(fileURLWithPath: file))
        }

        // The registry reads `Paths.support` and a profile for its own file, so
        // pointing those at the scratch tree is the whole wiring.
        Paths.support = scratch
        Paths.activeProfile = profile
        try writeTree(registry: baseRegistry)
        let registry = FaceRegistry(root: scratch, profile: profile)

        // --- the constants, from the engine ----------------------------------
        checkEqual("the match cosine is engine.py's", SFaceEmbedder.matchCosine,
                   (root["match_cosine"] as? NSNumber)?.doubleValue ?? -1)
        checkEqual("the cluster cosine is engine.py's", FaceRegistry.clusterCosine,
                   (root["cluster_cosine"] as? NSNumber)?.doubleValue ?? -1)
        checkEqual("the similar-faces limit is engine.py's", FaceRegistry.choiceLimit,
                   (root["choice_limit"] as? NSNumber)?.intValue ?? -1)
        checkEqual("the add-a-person choice cap is engine.py's", FaceRegistry.maxChoices,
                   (root["max_choices"] as? NSNumber)?.intValue ?? -1)
        checkEqual("the vectors are the engine's width", FaceRegistry.dim,
                   (root["dim"] as? NSNumber)?.intValue ?? -1)

        // --- people -----------------------------------------------------------

        let gotPeople = registry.people()
            .map { "\($0.name)|\($0.faces)|\($0.representative ?? "")" }
        let wantPeople = people.map {
            "\($0["name"] as? String ?? "")|\($0["faces"] as? Int ?? -1)|"
                + "\($0["representative"] as? String ?? "")"
        }
        checkEqual("people(): same names, counts and order in every row",
                   gotPeople, wantPeople)
        // The rule said out loud, so a future edit that "simplifies" it fails:
        // the person whose FIRST face has no thumbnail must show the first face
        // that has one.
        let quincyHashes = baseRegistry["Quincy"] ?? []
        if quincyHashes.count == 2 {
            check("Quincy's first face has no thumbnail on disk",
                  !thumbs.contains(quincyHashes[0]))
            checkEqual("...so the representative is the one that has",
                       gotPeople.first { $0.hasPrefix("Quincy|") },
                       "Quincy|2|\(quincyHashes[1])")
        } else {
            check("the fixture names a person whose first face has no thumbnail", false)
        }
        checkEqual("a person whose faces were all pruned is still listed",
                   gotPeople.contains { $0.hasPrefix("Zero|1|") }, true)

        // --- the matcher ------------------------------------------------------

        var sawHit = false
        var sawMiss = false
        for item in matches {
            let label = item["label"] as? String ?? "?"
            let detected = strings(item["detected"]).map(f32)
            let want = doubles(item["hits"])
            let got = registry.matches(vectors: detected, in: baseRegistry)
            checkEqual("matches: \(label) — the same names",
                       got.keys.sorted(), want.keys.sorted())
            var worst = 0.0
            for (name, score) in want { worst = max(worst, abs((got[name] ?? -1) - score)) }
            // Not bit-for-bit: numpy's `dot` sums in its own order and this
            // walks the vector in index order, so the two disagree in the last
            // couple of digits of a float64 sum. 1e-7 is five orders of
            // magnitude below the 0.001 that separates the fixture's two
            // threshold cases — it cannot hide a threshold that moved.
            checkClose("matches: \(label) — the same cosines (max |Δ| \(worst))",
                       worst, 0, 1e-7)
            if want.isEmpty { sawMiss = true } else { sawHit = true }
        }
        // 0.301 and 0.299 were built into the fixture on purpose: a gate that
        // only ever sees hits proves the matcher runs, not that it discriminates.
        check("a face at 0.301 matches and one at 0.299 does not — both were checked",
              sawHit && sawMiss)

        // A pruned hash must be skipped, never read as a zero vector.
        let everyCached = Array(cache.values).map(f32)
        check("a person whose vectors are gone matches nobody",
              !registry.matches(vectors: everyCached, in: baseRegistry)
                  .keys.contains("Zero"))
        check("every cached vector as a query still finds the people who are there",
              registry.matches(vectors: everyCached, in: baseRegistry)
                  .keys.sorted() == ["Bob Meyer", "Mia Ong", "Quincy"])

        // --- similar faces ----------------------------------------------------

        for item in similar {
            let name = item["name"] as? String ?? "?"
            let want = (strings(item["faces"]), (item["total"] as? NSNumber)?.intValue ?? -1)
            let got = await registry.similarFaces(name: name)
            checkEqual("similarFaces(\(name)): the same ranking and length",
                       got.faces, want.0)
            checkEqual("similarFaces(\(name)): the same total", got.total, want.1)
        }
        // The own-face exclusion as a property, not just a list.
        let lowercase = await registry.similarFaces(name: "quincy")
        check("the person's own faces are not offered back to them",
              Set(lowercase.faces).isDisjoint(with: Set(quincyHashes)))
        let spelledOut = await registry.similarFaces(name: "Quincy")
        check("a lowercase name resolves to the stored spelling",
              lowercase.faces == spelledOut.faces)
        checkEqual("a name nobody has bound is empty, not an error",
                   await registry.similarFaces(name: "Nobody").faces.count, 0)
        checkEqual("...and it reports no total rather than a wrong one",
                   await registry.similarFaces(name: "Nobody").total, 0)

        // --- forget -----------------------------------------------------------

        for item in forget {
            let name = item["name"] as? String ?? "?"
            try writeTree(registry: baseRegistry)
            let removed = try await registry.forget(name: name)
            checkEqual("forget(\(name)): the engine's count",
                       removed, (item["removed"] as? NSNumber)?.intValue ?? -1)
            checkEqual("forget(\(name)): the rest of the registry is untouched",
                       registry.registry(), registryOf(item["registry_after"]))
        }
        try writeTree(registry: baseRegistry)
        checkEqual("forget takes the name however it is spelled",
                   try await registry.forget(name: "QUINCY"), 2)
        check("...and the person is really gone", registry.registry()["Quincy"] == nil)
        // Only the binding goes: the faces stay cached, so the same face can be
        // bound to the right person afterwards.
        check("forget leaves the cached vectors alone",
              quincyHashes.allSatisfy { registry.vector(for: $0) != nil })

        // --- the representative ------------------------------------------------

        for item in representative {
            let label = item["label"] as? String ?? "?"
            let name = item["name"] as? String ?? "?"
            let hash = item["hash"] as? String ?? ""
            let wantPhoto = item["photo"] as? String
            let wantError = item["error"] as? String
            try writeTree(registry: baseRegistry)
            var gotError: String?
            do {
                _ = try await registry.setRepresentative(name: name, hash: hash)
            } catch {
                gotError = (error as? LocalizedError)?.errorDescription
                    ?? error.localizedDescription
            }
            checkEqual("setRepresentative: \(label) — the engine and the port agree on refusal",
                       gotError == nil, wantError == nil)
            if wantPhoto != nil {
                checkEqual("setRepresentative: \(label) — the chosen face leads \(name)'s list",
                           registry.registry()[name],
                           registryOf(item["registry_after"])[name] ?? [])
                check("setRepresentative: \(label) — and the list has no duplicate",
                      (registry.registry()[name] ?? []).count
                          == Set(registry.registry()[name] ?? []).count)
            } else {
                checkEqual("setRepresentative: \(label) — the registry is left alone",
                           registry.registry(), registryOf(item["registry_after"]))
                check("setRepresentative: \(label) — a face with no thumbnail is refused",
                      (wantError ?? "").contains("thumbnail"))
            }
        }
        try writeTree(registry: baseRegistry)
        _ = try await registry.setRepresentative(name: "Bob Meyer",
                                           hash: baseRegistry["Bob Meyer"]![0])
        checkEqual("re-picking the face a person already has is a no-op",
                   registry.registry()["Bob Meyer"]?.count, 1)

        // --- bind: merge, never replace ----------------------------------------

        for item in bind {
            let label = item["label"] as? String ?? "?"
            let name = item["name"] as? String ?? "?"
            let incoming = strings(item["hashes"])
            let engineBound = (item["engine_bound"] as? NSNumber)?.intValue ?? -1
            let engineKeys = strings(item["engine_keys"])
            let engineRegistry = registryOf(item["engine_registry_after"])
            try writeTree(registry: baseRegistry)
            let bound = try await registry.bind(name: name, hashes: incoming)
            let after = registry.registry()

            let engineStoredADuplicate = engineRegistry.values.contains {
                $0.count != Set($0).count
            }
            if engineKeys.count > 1 {
                // Divergence 1, pinned. `name_cluster` is the ONE face command in
                // engine.py that keys its name verbatim — `forget_person`,
                // `set_photo`, `set_representative` and `similar_faces` all
                // case-fold. Keying verbatim is what makes "quincy" a second
                // person beside "Quincy", so the port resolves the name's case
                // the way the rest of the engine's face block does.
                let stored = item["swift_expected_key"] as? String ?? ""
                checkEqual("bind: \(label) — the engine created a second person",
                           engineKeys.count, 2)
                checkEqual("bind: \(label) — the port creates no new person",
                           after.keys.count, baseRegistry.keys.count)
                checkEqual("bind: \(label) — it joins the stored spelling",
                           after[stored]?.contains(incoming[0]), true)
                checkEqual("bind: \(label) — and nothing beside it",
                           after.keys.contains {
                               $0.casefolded == stored.casefolded && $0 != stored
                           }, false)
                checkEqual("bind: \(label) — the engine's verbatim key is what it fixed",
                           stored, engineKeys[0])
            } else if engineStoredADuplicate {
                // Divergence 2, pinned. The engine dedupes against what is
                // already STORED, so a hash repeated inside one request is
                // appended twice; the port collapses it, because a registry list
                // holding one face twice is a row drawn twice waiting to happen.
                checkEqual("bind: \(label) — the engine stored a hash twice", true, true)
                let alreadyThere = Set(baseRegistry[name] ?? [])
                checkEqual("bind: \(label) — the port binds each new face once",
                           bound, Set(incoming).subtracting(alreadyThere).count)
                let merged = after[name] ?? []
                checkEqual("bind: \(label) — the list has no duplicate",
                           merged.count, Set(merged).count)
                checkEqual("bind: \(label) — every face that was there survives",
                           alreadyThere.isSubset(of: Set(merged)), true)
                checkEqual("bind: \(label) — every face in the request is bound",
                           Set(incoming).isSubset(of: Set(merged)), true)
            } else {
                // No divergence: the port must reproduce the engine exactly.
                checkEqual("bind: \(label) — the engine's count", bound, engineBound)
                checkEqual("bind: \(label) — the registry matches the engine's",
                           after, engineRegistry)
            }
        }
        try writeTree(registry: baseRegistry)
        checkEqual("bind refuses a blank name",
                   (try? await registry.bind(name: "   ", hashes: ["x"])) == nil, true)
        checkEqual("bind refuses an empty face list",
                   (try? await registry.bind(name: "Ann", hashes: [])) == nil, true)

        // --- clustering, against engine.face_clusters --------------------------

        let clusterVectors = (clusters["vectors"] as? [String: String] ?? [:]).mapValues(f32)
        let clusterHashes = strings(clusters["hashes"])
        let partition = (clusters["partition"] as? [[String]]) ?? []
        checkEqual("the generator verified the partition is order-independent",
                   (clusters["orders_agreed"] as? NSNumber)?.intValue ?? 0, 7)
        checkEqual("the fixture's clusters are the sizes it built",
                   partition.map(\.count).sorted(), [2, 3, 4])

        // Faces arrive biggest-first, which is the order `detect_faces` sees
        // them in, so a cluster's representative is its most prominent crop.
        let seen = Dictionary(uniqueKeysWithValues: clusterHashes.enumerated().map {
            index, hash in
            (hash, (area: Double(clusterHashes.count - index),
                    vector: clusterVectors[hash] ?? []))
        })
        let chosen = FaceRegistry.choose(seen: seen)
        let gotPartition = partitionClumps(seen: seen, chosen: chosen)
            .map { $0.sorted() }.sorted { $0.count > $1.count }
        checkEqual("clustering reproduces engine.face_clusters' partition",
                   gotPartition, partition.map { $0.sorted() }.sorted { $0.count > $1.count })

        // The chooser's own rules: five at most, one per person, biggest first.
        checkEqual("the chooser returns at most its cap",
                   chosen.count, min(FaceRegistry.maxChoices, partition.count))
        checkEqual("...one representative per cluster", Set(chosen).count, chosen.count)
        checkEqual("...and the most prominent face leads", chosen.first, clusterHashes[0])
        checkEqual("a single face is one choice", FaceRegistry.choose(seen: [
            clusterHashes[0]: (area: 1, vector: clusterVectors[clusterHashes[0]] ?? []),
        ]).count, 1)
        checkEqual("no faces is no choices", FaceRegistry.choose(seen: [:]).count, 0)

        // --- the hash is the engine's formula ---------------------------------
        //
        // `sha256(112×112×3 BGR pixels)[:32]`. Only the shape can be checked
        // here — the value needs a real face, and `test_face_engine.swift`
        // checks it against cv2's own crop.
        let sample = [UInt8](repeating: 7, count: 112 * 112 * 3)
        let hashed = FaceRegistry.hash(of: sample)
        checkEqual("a crop hash is 32 hex characters", hashed.count, 32)
        check("...and hex at that", hashed.allSatisfy(\.isHexDigit))
        check("...and stable", FaceRegistry.hash(of: sample) == hashed)
        check("...and it changes with the pixels",
              FaceRegistry.hash(of: sample.dropLast() + CollectionOfOne(UInt8(8))) != hashed)

        // --- the classifier's face engine follows the active profile ---------
        //
        // Which name belongs to which face is one person's judgement, so the
        // registry is per profile. `FaceStore.reload(profile:)` drops its own
        // cached registry for that reason, but `AnalysisEngine` holds ONE
        // `CoreMLClassifier` for the life of the app, and its registry is
        // built on first use. Cached across a switch, it answers the new
        // profile's suggestions out of the old profile's `faces.json`.
        //
        // Two profiles with disjoint names, so a leak is visible as a name
        // that cannot belong to the profile asking.
        for (who, person) in [("alpha", "Alpha Only"), ("beta", "Beta Only")] {
            let dir = ProfileBundle.dir(who, root: scratch)
            try fm.createDirectory(atPath: dir, withIntermediateDirectories: true)
            try JSONSerialization.data(withJSONObject: [person: ["face-\(who)"]])
                .write(to: URL(fileURLWithPath:
                    (dir as NSString).appendingPathComponent("faces.json")))
        }

        Paths.activeProfile = "alpha"
        let lifetimeClassifier = CoreMLClassifier(root: scratch)
        let underAlpha = await lifetimeClassifier.faceEngine()
        checkEqual("the face engine is built for the profile that is active",
                   underAlpha.profile, "alpha")
        checkEqual("...and reads that profile's names",
                   underAlpha.people().map(\.name), ["Alpha Only"])

        let againUnderAlpha = await lifetimeClassifier.faceEngine()
        check("the engine is reused while the profile has not moved",
              againUnderAlpha === underAlpha)

        Paths.activeProfile = "beta"
        let underBeta = await lifetimeClassifier.faceEngine()
        checkEqual("switching profile rebuilds the face engine for the new one",
                   underBeta.profile, "beta")
        check("...as a different instance, not the old one relabelled",
              underBeta !== underAlpha)
        checkEqual("...reading the new profile's names, not the old profile's",
                   underBeta.people().map(\.name), ["Beta Only"])
        check("no name from the previous profile survives the switch",
              !underBeta.people().contains { $0.name == "Alpha Only" })

        // Back again: the rule is not one-way, and the first profile's own
        // names are still its own.
        Paths.activeProfile = "alpha"
        let backToAlpha = await lifetimeClassifier.faceEngine()
        checkEqual("switching back rebinds to the first profile",
                   backToAlpha.profile, "alpha")
        checkEqual("...with its own names intact",
                   backToAlpha.people().map(\.name), ["Alpha Only"])
        Paths.activeProfile = profile

        if failures > 0 {
            print("\(failures) FAILED")
            exit(1)
        }
        exit(0)
    }

    /// Which clump each face falls into, derived from the VECTORS rather than
    /// from the clustering's own bookkeeping — a bug in the bookkeeping cannot
    /// then make the test agree with itself.
    static func partitionClumps(seen: [String: (area: Double, vector: [Float])],
                                chosen: [String]) -> [[String]] {
        func nearest(_ vector: [Float]) -> String? {
            chosen.max { a, b in
                SFaceEmbedder.cosine(vector, seen[a]?.vector ?? [])
                    < SFaceEmbedder.cosine(vector, seen[b]?.vector ?? [])
            }
        }
        var out: [String: [String]] = [:]
        for (hash, sighting) in seen {
            guard let representative = nearest(sighting.vector) else { continue }
            out[representative, default: []].append(hash)
        }
        return Array(out.values)
    }
}
