// The look-alike search, checked against engine.py's own answers.
//
// `tag_candidates` decides what the tag-review playlist offers, and every way of
// getting it subtly wrong still returns a plausible list: a prototype built from
// the wrong videos, a baseline measured over raw frames instead of per-video
// means, a margin applied as a similarity, a sort that is not stable, a pool
// taken from `library.tags` (which holds only the videos that ALREADY have the
// tag — the bug that once made every tag report "no candidates"). So this
// replays a fixture generated by calling the real `engine.tag_candidates`
// (docs/coreml-spike/lookalike_parity.py) and demands identical output.
//
// What the fixture guarantees is in it, so the branches are all exercised:
// three videos that really do look alike (one barely clearing the margin), one
// that is close but below it, a video whose frames cancel to a zero vector, a
// video with no cached frames, and a video with no hashes at all.
//
// Run: Tests/run_look_alikes.sh

import Foundation

@main
struct LookAlikesTest {
    static func main() {
        var failures = 0
        func check(_ name: String, _ cond: Bool) {
            print(cond ? "ok   \(name)" : "FAIL \(name)")
            if !cond { failures += 1 }
        }
        func checkEqual<T: Equatable>(_ name: String, _ got: T, _ want: T) {
            let ok = got == want
            print(ok ? "ok   \(name)" : "FAIL \(name) — got \(got), want \(want)")
            if !ok { failures += 1 }
        }
        func checkClose(_ name: String, _ got: Double, _ want: Double, _ tol: Double) {
            let ok = abs(got - want) <= tol
            print(ok ? "ok   \(name)" : "FAIL \(name) — got \(got), want \(want)")
            if !ok { failures += 1 }
        }

        let args = CommandLine.arguments
        let path = args.count > 1
            ? args[1]
            : NSHomeDirectory() + "/fvp-coreml-models/lookalike_fixture.json"
        guard let raw = FileManager.default.contents(atPath: path),
              let root = (try? JSONSerialization.jsonObject(with: raw)) as? [String: Any],
              let cases = root["cases"] as? [[String: Any]] else {
            print("SKIP look-alikes — no fixture at \(path)")
            print("     build it with: /opt/anaconda3/bin/python3 docs/coreml-spike/lookalike_parity.py")
            exit(0)
        }

        func bytes(_ b64: String) -> Data { Data(base64Encoded: b64) ?? Data() }
        func f32(_ b64: String) -> [Float] {
            let d = bytes(b64)
            var out = [Float](repeating: 0, count: d.count / 4)
            _ = out.withUnsafeMutableBytes { d.copyBytes(to: $0) }
            return out
        }
        func f64(_ b64: String) -> [Double] {
            let d = bytes(b64)
            var out = [Double](repeating: 0, count: d.count / 8)
            _ = out.withUnsafeMutableBytes { d.copyBytes(to: $0) }
            return out
        }

        var frames: [String: [Float]] = [:]
        for (h, v) in root["frames"] as! [String: String] { frames[h] = f32(v) }
        let read: (String) -> [Float]? = { frames[$0] }     // a miss is a miss, as on disk

        let videos: [(key: String, hashes: [String])] =
            (root["videos"] as! [[String: Any]]).map {
                ($0["key"] as! String, $0["hashes"] as! [String])
            }
        let byKey = Dictionary(videos.map { ($0.key, $0.hashes) }, uniquingKeysWith: { a, _ in a })

        checkEqual("the fixture's margin is the ported constant",
                   LookAlikes.margin, root["margin"] as! Double)
        checkEqual("...and its minimum is too",
                   LookAlikes.minVideos, root["min_videos"] as! Int)

        // --- 1. the collection step, on its own -----------------------------
        let wantMeans = root["means"] as! [String: String]
        let zeroVideo = byKey["v_zero"]!
        check("frames that cancel to a zero vector yield no mean vector",
              LookAlikes.meanVector(zeroVideo, read: read) == nil)
        check("a video with nothing cached yields no mean vector",
              LookAlikes.meanVector(byKey["v_nocache"]!, read: read) == nil)
        check("a video with no hashes yields no mean vector",
              LookAlikes.meanVector([], read: read) == nil)

        var worstMean = 0.0
        var checked = 0
        for (key, hashes) in byKey {
            guard let want = wantMeans[key], let got = LookAlikes.meanVector(hashes, read: read) else { continue }
            let wantVec = f64(want)
            for i in 0..<min(got.count, wantVec.count) {
                worstMean = max(worstMean, abs(got[i] - wantVec[i]))
            }
            checked += 1
        }
        print("     per-video mean max |Δ| = \(worstMean) over \(checked) videos")
        check("every video with usable frames matches numpy's mean vector",
              checked >= 30 && worstMean < 1e-12)

        // --- 2. every case, through the ranked search ------------------------
        var totalCandidates = 0
        for one in cases {
            let name = one["name"] as? String ?? "?"
            let tag = one["tag"] as! String
            let limit = (one["limit"] as? Int) ?? LookAlikes.defaultLimit
            let tagged = (one["tagged"] as! [String]).map { ($0, byKey[$0]!) }
            let pool = (one["pool"] as! [String]).map { ($0, byKey[$0]!) }
            let want = one["expected"] as! [String: Any]

            let got = LookAlikes.rank(tag: tag, tagged: tagged, pool: pool, read: read, limit: limit)

            checkEqual("\(name): tag echoed", got.tag, want["tag"] as? String ?? "")
            checkEqual("\(name): candidates offered", got.candidates.count,
                       (want["candidates"] as! [[String: Any]]).count)
            checkEqual("\(name): unseen pool", got.unseenPool, want["unseen_pool"] as! Int)
            // The count is what engine.py reports and what this comparison is
            // built on; the KEYS are what the app needs, because the only thing
            // that makes such a video visible to the search is analysing it.
            checkEqual("\(name): every unseen video is named, not just counted",
                       got.unseen.count, got.unseenPool)
            let poolKeys = Set(one["pool"] as! [String])
            check("\(name): and each name is a pool video, never the tag's own",
                  got.unseen.allSatisfy { poolKeys.contains($0) })
            checkEqual("\(name): refusal reason",
                       got.reason ?? "", want["reason"] as? String ?? "")

            for (i, wantCand) in (want["candidates"] as! [[String: Any]]).enumerated() {
                guard i < got.candidates.count else { break }
                checkEqual("\(name): rank \(i + 1) is \(wantCand["key"] as! String)",
                           got.candidates[i].key, wantCand["key"] as! String)
                // the score is reported rounded to 4 decimals, so it must match
                // exactly — a last-bit difference in the margin is invisible
                checkEqual("\(name): rank \(i + 1) score matches to the digit shown",
                           got.candidates[i].score, wantCand["score"] as! Double)
            }
            totalCandidates += got.candidates.count
        }
        check("the fixture actually produced candidates to compare", totalCandidates >= 5)

        // --- 3. the boundaries this search rests on --------------------------
        // The margin itself: a video exactly on it is offered.
        let proto = (0..<2).map { _ in LookAlikes.unit([1.0, 0.0])! }
        checkEqual("a unit vector stays unit", proto[0], [1.0, 0.0])
        check("a zero vector has no direction to keep", LookAlikes.unit([0.0, 0.0]) == nil)
        checkEqual("four decimals, as the engine reports",
                   LookAlikes.round4(0.21724999), 0.2172)
        checkEqual("...and it rounds the other way too",
                   LookAlikes.round4(0.21725001), 0.2173)
        checkEqual("mean of an empty list is nothing", LookAlikes.mean([]) == nil, true)

        // A pool taken from the wrong place is the classic failure here: a tag's
        // OWN videos are in `library.tags`, so a pool built from it searches
        // nothing. The fixture's tagged videos must be absent from its pool.
        let firstTagged = Set(cases[0]["tagged"] as! [String])
        let firstPool = Set(cases[0]["pool"] as! [String])
        check("the fixture's pool excludes the tagged videos (the pitfall-16 shape)",
              firstTagged.isDisjoint(with: firstPool))
        check("...and the pool is the whole rest of the library",
              firstPool.count == byKey.count - firstTagged.count)

        // Order is load-bearing: equal scores break by library order, so the
        // same pool in a different order must not silently reorder equal rows.
        let a = LookAlikes.rank(tag: "t", tagged: [("a", byKey["v_kite1"]!), ("b", byKey["v_kite2"]!)],
                                pool: [("p1", byKey["v_plain00"]!), ("p2", byKey["v_plain01"]!)],
                                read: read)
        let b = LookAlikes.rank(tag: "t", tagged: [("a", byKey["v_kite1"]!), ("b", byKey["v_kite2"]!)],
                                pool: [("p1", byKey["v_plain00"]!), ("p2", byKey["v_plain01"]!)],
                                read: read)
        checkEqual("the same input ranks the same way twice",
                   a.candidates.map { $0.key }, b.candidates.map { $0.key })

        // --- what the app analyses for itself --------------------------------
        //
        // A tagged video with no embeddings is not a prototype, so a tag can
        // hold two videos and still refuse. The app used to analyse exactly the
        // shortfall — one short of `minVideos` — which answered "what else looks
        // like this" from a fraction of what the user had taught it: 36 tagged
        // videos, 4 prototypes. It now analyses the tag's unanalysed videos
        // before searching, so the only constant this file can still pin is the
        // threshold the refusal is built on. What the app does with it is
        // PlaylistSidebar's business and is not reachable from here.
        checkEqual("two tagged videos is what the search needs", LookAlikes.minVideos, 2)

        // The refusal that threshold produces, from the other side: a
        // tagged video whose frames are not cached contributes nothing, so the
        // count really is of analysed tagged videos.
        let empty = LookAlikes.rank(tag: "t", tagged: [("a", [String]()), ("b", byKey["v_kite1"]!)],
                                    pool: [("p1", byKey["v_plain00"]!)], read: read)
        check("a tagged video with no cached frames cannot be a prototype",
              empty.candidates.isEmpty)
        check("...and says so in the engine's own words, with the count",
              (empty.reason ?? "").contains("need 2+ tagged videos"))

        // --- only offer what is still there ----------------------------------
        //
        // A folder that moved leaves the old key in the store with its vectors,
        // and the search will rank it. That row carries the SAME file name as
        // the video the user may have just rejected — the reason a rejection
        // can look like it did not take — and it cannot be played or accepted.
        let pool = [LookAlikes.Candidate(key: "a", score: 0.31),
                    LookAlikes.Candidate(key: "b", score: 0.22),
                    LookAlikes.Candidate(key: "c", score: 0.14)]
        let live = LookAlikes.live(pool) { $0 != "b" }
        checkEqual("candidates whose file is still there come back in order",
                   live.live.map(\.key), ["a", "c"])
        checkEqual("...and the ones that are not are counted, not silently dropped",
                   live.gone, 1)
        checkEqual("...with their scores untouched (this filters, it does not re-rank)",
                   live.live.map(\.score), [0.31, 0.14])
        let noneGone = LookAlikes.live(pool) { _ in true }
        checkEqual("nothing gone, nothing to report", noneGone.gone, 0)
        checkEqual("...and every candidate survives", noneGone.live.count, 3)
        checkEqual("all gone is all counted", LookAlikes.live(pool) { _ in false }.gone, 3)
        checkEqual("an empty shortlist has nothing to check",
                   LookAlikes.live([LookAlikes.Candidate]()) { _ in false }.gone, 0)

        // --- 4. widening the search instead of asking the user to ------------
        //
        // The app no longer answers a thin search with "run Classify to widen
        // the search": it analyses the videos it cannot read, then re-asks.
        // Which videos is this function's whole job, and every way of getting
        // it wrong is quiet — a set that is too small leaves the search thin,
        // and a set that keeps coming back is a run that never ends. The counts
        // matter as much as the list: the note the user reads is built from
        // them, and a number the app cannot explain is what this replaced.
        let noRefusal: (String) -> Bool = { _ in false }
        let oneBad = LookAlikes.widening(unreadable: ["b"], unscored: [], tried: [],
                                         skip: noRefusal)
        checkEqual("a video the engine cannot read is handed over to be re-analysed",
                   oneBad.batch, ["b"])
        checkEqual("...and it is one of one on offer", oneBad.offered, 1)

        let bothKinds = LookAlikes.widening(unreadable: ["b", "a"], unscored: ["c", "a"],
                                            tried: [], skip: noRefusal)
        checkEqual("both kinds come back once each, in library order",
                   bothKinds.batch, ["a", "b", "c"])
        checkEqual("...and the offered count does not double-count the overlap",
                   bothKinds.offered, 3)

        // The loop this prevents: a cache write is best-effort, so a video that
        // comes back from a run with nothing on disk would be handed over again
        // by the very next search, for as long as the app is open.
        let triedOnce = LookAlikes.widening(unreadable: ["a", "b"], unscored: [], tried: ["a"],
                                            skip: noRefusal)
        checkEqual("a video already re-analysed this session is not handed over twice",
                   triedOnce.batch, ["b"])
        checkEqual("...it is counted instead, so the app can say why", triedOnce.alreadyTried, 1)
        checkEqual("...and it is not counted as on offer", triedOnce.offered, 1)

        let refusedOne = LookAlikes.widening(unreadable: ["a", "b", "c"], unscored: [], tried: [],
                                             skip: { $0 == "b" })
        checkEqual("the caller's own refusal is honoured, per key",
                   refusedOne.batch, ["a", "c"])
        checkEqual("...and reported as refused, not as nothing to do", refusedOne.refused, 1)

        let nothing = LookAlikes.widening(unreadable: [], unscored: [], tried: [],
                                          skip: noRefusal)
        checkEqual("nothing unreadable is nothing to do", nothing.batch, [String]())
        check("...and says so", nothing.isEmpty)
        checkEqual("...with no counts to explain", nothing.offered + nothing.refused,
                   nothing.alreadyTried)
        checkEqual("a key that names no video is dropped",
                   LookAlikes.widening(unreadable: [""], unscored: ["a"], tried: [],
                                       skip: noRefusal).batch,
                   ["a"])
        let capped = LookAlikes.widening(unreadable: ["a", "b", "c"], unscored: [], tried: [],
                                         skip: noRefusal, limit: 2)
        checkEqual("one pass is bounded, and takes the first keys in library order",
                   capped.batch, ["a", "b"])
        checkEqual("...and still says how many there were", capped.offered, 3)
        checkEqual("an empty batch is what a zero limit means",
                   LookAlikes.widening(unreadable: ["a"], unscored: [], tried: [],
                                       skip: noRefusal, limit: 0).batch,
                   [String]())
        // The batch size is a limit on what ONE pass runs, never on what the
        // app will eventually analyse: the same call with no limit has to see
        // the whole library, or a big one would be searched against a quarter
        // of itself for ever.
        let wholeLibrary = (0..<400).map { "v\($0)" }
        checkEqual("the whole library is on offer, past one batch",
                   LookAlikes.widening(unreadable: wholeLibrary, unscored: [], tried: [],
                                       skip: noRefusal, limit: Int.max).offered,
                   400)
        checkEqual("and the batch the app actually runs is smaller than that",
                   LookAlikes.widening(unreadable: wholeLibrary, unscored: [], tried: [],
                                       skip: noRefusal).batch.count,
                   LookAlikes.wideningBatch)
        check("which is fewer than the library, so the note says 'of'",
              LookAlikes.wideningBatch < wholeLibrary.count)

        print(failures == 0 ? "ALL PASS look-alikes" : "\(failures) FAILURES")
        exit(failures == 0 ? 0 : 1)
    }
}
