// The logistic heads, checked against engine.py's own fit.
//
// A ported trainer that is subtly wrong still trains: a transposed split, a
// hold-out that leaks frames, a gate that fires on 3 videos, a lambda applied
// after the update instead of before — every one of those produces a head that
// scores plausible numbers. So this test does not check that the fit "works".
// It replays a fixture generated by the REAL `engine.train` / `engine.train_nsfw`
// (docs/coreml-spike/head_parity.py) and demands the same videos, the same
// splits, the same weights, the same held-out precision/recall, and the same
// refusal strings — the copy the UI shows.
//
// The three boundaries that matter to the caller are checked directly too:
//  - a frame exactly on the cut IS a vote (`>=`, not `>`);
//  - a video with no cached frames is dropped, not zero-filled — which moves
//    the hold-out for every other video;
//  - a head is scored in float32, the width the Python path scores in.
//
// `@main` rather than top-level code: this file is compiled alongside
// LogisticHead.swift, and only a file literally named main.swift may carry
// top-level statements.
//
// Run: Tests/run_logistic_head.sh

@testable import FVPModel
import Foundation

@main
struct LogisticHeadTest {
    static func main() {
        var failures = 0
        func check(_ name: String, _ cond: Bool) {
            print(cond ? "ok   \(name)" : "FAIL \(name)")
            if !cond { failures += 1 }
        }
        func checkEqual<T: Equatable>(_ name: String, _ got: T, _ want: T) {
            let ok = got == want
            print(ok ? "ok   \(name)" : "FAIL \(name) — got \(got), want \(want)")
            if !ok { failures += 1 }
        }
        func checkClose(_ name: String, _ got: Double, _ want: Double, _ tol: Double) {
            let ok = abs(got - want) <= tol
            print(ok ? "ok   \(name)" : "FAIL \(name) — got \(got), want \(want)")
            if !ok { failures += 1 }
        }

        let args = CommandLine.arguments
        let path = args.count > 1
            ? args[1]
            : NSHomeDirectory() + "/fvp-coreml-models/head_fixture.json"
        guard let raw = FileManager.default.contents(atPath: path),
              let root = (try? JSONSerialization.jsonObject(with: raw)) as? [String: Any],
              let expected = root["expected"] as? [String: Any] else {
            print("SKIP logistic head — no fixture at \(path)")
            print("     build it with: /opt/anaconda3/bin/python3 docs/coreml-spike/head_parity.py")
            exit(0)
        }

        func f32(_ b64: String) -> [Float] {
            guard let d = Data(base64Encoded: b64) else { return [] }
            var out = [Float](repeating: 0, count: d.count / 4)
            _ = out.withUnsafeMutableBytes { d.copyBytes(to: $0) }
            return out
        }
        func f64(_ b64: String) -> [Double] {
            guard let d = Data(base64Encoded: b64) else { return [] }
            var out = [Double](repeating: 0, count: d.count / 8)
            _ = out.withUnsafeMutableBytes { d.copyBytes(to: $0) }
            return out
        }

        // --- decode the fixture --------------------------------------------
        let dim = root["dim"] as! Int
        let cached = Set(root["cached"] as! [String])
        var frameMap: [String: [Float]] = [:]
        for (h, v) in root["frames"] as! [String: String] { frameMap[h] = f32(v) }
        let videos: [(key: String, hashes: [String])] =
            (root["videos"] as! [[String: Any]]).map {
                ($0["key"] as! String, $0["hashes"] as! [String])
            }
        let read: (String) -> [Float]? = { h in
            guard cached.contains(h) else { return nil }      // the video with nothing cached
            return frameMap[h]
        }

        // --- 1. collection: mean of cached frames, unit-norm ----------------
        let dataset = HeadDataset.build(frames: videos, read: read)
        let wantKeys = expected["keys"] as! [String]
        check("the video with no cached frames is dropped, not zero-filled",
              dataset.keys.count == videos.count - 1 && dataset.keys.count == 40)
        checkEqual("the videos the engine used, in its order", dataset.keys, wantKeys)
        checkEqual("every row is the encoder width", dataset.dim, dim)

        let wantX = f64(expected["X"] as! String)
        var worstRow = 0.0
        for i in 0..<min(dataset.vectors.count, wantKeys.count) {
            for j in 0..<dim {
                worstRow = max(worstRow, abs(dataset.vectors[i][j] - wantX[i * dim + j]))
            }
        }
        print("     mean-vector max |Δ| = \(worstRow)")
        checkClose("the collected mean vectors match numpy's", worstRow, 0, 1e-12)

        // --- 2. the fit, tag by tag ----------------------------------------
        let tags: [(tag: String, labels: [String: Bool])] =
            (root["tags"] as! [[String: Any]]).map {
                ($0["tag"] as! String, $0["labels"] as! [String: Bool])
            }
        let (heads, fits) = LogisticTrainer.fitTags(tags, dataset: dataset)
        let wantFits = expected["fits"] as! [[String: Any]]

        checkEqual("one fit record per tag, in the order asked", fits.map { $0.tag },
                   wantFits.map { $0["tag"] as! String })
        for (i, want) in wantFits.enumerated() {
            let tag = want["tag"] as! String
            guard i < fits.count else { break }
            let got = fits[i]
            checkEqual("\(tag): fitted", got.fitted, want["fitted"] as! Bool)
            checkEqual("\(tag): refusal text is the engine's own",
                       got.reason ?? "", want["reason"] as? String ?? "")
            checkEqual("\(tag): videos counted", got.videos ?? -1, want["videos"] as? Int ?? -1)
            checkEqual("\(tag): held out after the split", got.heldOut ?? -1,
                       want["held_out"] as? Int ?? -1)
            if got.fitted {
                // engine.py keeps only the rounded numbers; the raw ones come
                // from rescoring the stored float32 head over the same videos.
                checkClose("\(tag): held-out precision", got.precision ?? -1,
                           want["precision_raw"] as! Double, 1e-9)
                checkClose("\(tag): held-out recall", got.recall ?? -1,
                           want["recall_raw"] as! Double, 1e-9)
            }
        }

        let wantHeads = expected["heads"] as! [String: [String: Any]]
        checkEqual("a head exists for exactly the tags that fitted",
                   heads.keys.sorted(), wantHeads.keys.sorted())
        var worstW = 0.0, worstB = 0.0
        for (tag, want) in wantHeads {
            guard let head = heads[tag] else { continue }
            let w = f32(want["w"] as! String)
            for i in 0..<min(w.count, head.w.count) {
                worstW = max(worstW, abs(Double(w[i] - head.w[i])))
            }
            worstB = max(worstB, abs((want["b"] as! Double) - Double(head.b)))
            checkClose("\(tag): n stored as float32", Double(head.n), want["n"] as! Double, 0)
        }
        print("     fitted weight max |Δ| = \(worstW)   bias max |Δ| = \(worstB)")
        checkClose("the fitted weights match numpy's to float32 precision", worstW, 0, 1e-6)
        checkClose("the fitted bias matches numpy's", worstB, 0, 1e-6)

        // --- 3. the Safe/NSFW head -----------------------------------------
        // A different population on purpose: only the marked videos, so this
        // split does NOT match the tag split.
        let nsfwLabels = root["nsfw_labels"] as! [String: Bool]
        let nsfwVideos = videos.filter { nsfwLabels[$0.key] != nil }
        let nsfwData = HeadDataset.build(frames: nsfwVideos, read: read)
        let (nsfwHead, nsfwFit) = LogisticTrainer.fitNSFW(labels: nsfwLabels, dataset: nsfwData)
        let wantNsfwFit = expected["nsfw_fit"] as! [String: Any]
        let wantNsfwHead = expected["nsfw_head"] as! [String: Any]

        checkEqual("nsfw: only marked videos are collected", nsfwData.keys.count,
                   wantNsfwFit["videos"] as! Int)
        checkEqual("nsfw: fitted", nsfwFit.fitted, wantNsfwFit["fitted"] as! Bool)
        checkEqual("nsfw: held out after its own split", nsfwFit.heldOut ?? -1,
                   wantNsfwFit["held_out"] as! Int)
        checkClose("nsfw: held-out precision", nsfwFit.precision ?? -1,
                   wantNsfwFit["precision_raw"] as! Double, 1e-9)
        checkClose("nsfw: held-out recall", nsfwFit.recall ?? -1,
                   wantNsfwFit["recall_raw"] as! Double, 1e-9)
        if let head = nsfwHead {
            let w = f32(wantNsfwHead["w"] as! String)
            var worst = 0.0
            for i in 0..<min(w.count, head.w.count) { worst = max(worst, abs(Double(w[i] - head.w[i]))) }
            print("     nsfw weight max |Δ| = \(worst)")
            checkClose("nsfw: weights match numpy's", worst, 0, 1e-6)
            checkClose("nsfw: bias matches numpy's", Double(head.b),
                       wantNsfwHead["b"] as! Double, 1e-6)
            checkEqual("nsfw: n is the marked-video count",
                       Double(head.n), wantNsfwHead["n"] as! Double)
        } else {
            check("nsfw: a head was fitted", false)
        }

        // --- 4. the boundaries the caller depends on ------------------------
        let flipped = LogisticHead(w: [1, 0], b: 0, n: 0)
        checkClose("sigmoid(0) is exactly the cut", Double(flipped.score([0, 0])), 0.5, 1e-7)
        checkEqual("a frame exactly ON the cut is a vote", flipped.hits([[0, 0]]), 1)
        checkEqual("a frame below the cut is not", flipped.hits([[-1, 0]]), 0)
        checkEqual("hits counts frames, not videos", flipped.hits([[0, 0], [5, 0], [-1, 0]]), 2)
        check("a wrong-width vector scores nothing, not something",
              flipped.score([0, 0, 0]).isNaN)
        check("dim is the weight width", flipped.matches(dim: 2) && !flipped.matches(dim: 3))

        let empty = HeadDataset(keys: [], vectors: [])
        let (noHeads, noFits) = LogisticTrainer.fitTags([("t", ["a": true])], dataset: empty)
        check("no videos, no heads", noHeads.isEmpty && noFits.isEmpty)
        let (noNsfw, nsfwRefusal) = LogisticTrainer.fitNSFW(labels: [:], dataset: empty)
        check("no videos refuses the nsfw head out loud",
              noNsfw == nil && !nsfwRefusal.fitted && nsfwRefusal.reason != nil)

        // The gate is a refusal, not a crash: 3 accepted videos must not fit.
        let tiny = HeadDataset(keys: ["a", "b", "c", "d", "e", "f", "g", "h"],
                               vectors: Array(repeating: Array(repeating: 0.0, count: dim), count: 8))
        let (tinyHeads, tinyFits) = LogisticTrainer.fitTags(
            [("t", ["a": true, "b": true, "c": true, "d": false, "e": false, "f": false, "g": false, "h": false])],
            dataset: tiny)
        check("3 accepted does not fit a head", tinyHeads.isEmpty && tinyFits.count == 1)
        checkEqual("and says why, in the engine's words",
                   tinyFits[0].reason ?? "", "need 4+ accepted and 4+ rejected videos (have 3/5)")

        // --- 5. the shape the report travels in -----------------------------
        let fit = HeadFit(tag: "t", fitted: true, reason: nil, videos: 9, heldOut: 2,
                          precision: 0.5, recall: 0.25)
        let encoded = try! JSONEncoder().encode(fit)
        let text = String(data: encoded, encoding: .utf8)!
        check("HeadFit encodes held_out the way the engine writes it",
              text.contains("\"held_out\":2") && text.contains("\"precision\":0.5"))

        print(failures == 0 ? "ALL PASS logistic head" : "\(failures) FAILURES")
        exit(failures == 0 ? 0 : 1)
    }
}
