// The whole suggester, checked against engine.py's own answers.
//
// `suggest_tags` merges FOUR sources into one ranked list, and every way of
// getting it subtly wrong still produces a plausible set of chips: a zero-shot
// list that was capped before the other sources could promote an entry, a head
// that is allowed to REPLACE a stronger entry instead of only a weaker one, a
// tag pair that emits both chips (or one on a Safe video), a library
// prototype offered for a tag whose videos were never analysed, a sort that is
// not stable so equal confidences come back in a different order, a cap applied
// before the ranking rather than after. So this replays a fixture generated by
// calling the real `engine.suggest_tags`
// (docs/coreml-spike/suggest_parity.py) and demands identical output —
// including the confidences the UI will show, and their order.
//
// The fixture aims each frame at a chosen margin over the background pool
// (0.0205 over the bar, 0.0195 under it, 0.35, 0.05, −0.15 …) and refuses to
// emit itself unless every case reached the branch it was written for, so the
// frame counts and hit counts below are a real test of the thresholds rather
// than a coincidence of random vectors.
//
// Run: Tests/run_tag_suggester.sh

import Foundation

@main
struct TagSuggesterTest {
    static func main() {
        var failures = 0
        func check(_ name: String, _ cond: Bool) {
            print(cond ? "ok   \(name)" : "FAIL \(name)")
            if !cond { failures += 1 }
        }
        func checkEqual<T: Equatable>(_ name: String, _ got: T, _ want: T) {
            let ok = got == want
            print(ok ? "ok   \(name)" : "FAIL \(name) — got \(got), want \(want)")
            if !ok { failures += 1 }
        }
        /// Tag, confidence, frames, source — the whole of a candidate.
        func checkList(_ name: String, _ got: [TagSuggester.Candidate],
                       _ want: [(String, Double, Int, String)]) {
            let flat = got.map { ($0.tag, $0.confidence, $0.frames, $0.source) }
            let same = flat.count == want.count && zip(flat, want).allSatisfy {
                $0.0 == $1.0 && $0.1 == $1.1 && $0.2 == $1.2 && $0.3 == $1.3
            }
            let shown = got.map { "\($0.tag)=\($0.confidence)/\($0.frames)/\($0.source)" }
            print(same ? "ok   \(name)"
                       : "FAIL \(name)\n       got  \(shown)\n       want \(want.map { "\($0.0)=\($0.1)/\($0.2)/\($0.3)" })")
            if !same { failures += 1 }
        }

        let args = CommandLine.arguments
        let path = args.count > 1
            ? args[1]
            : NSHomeDirectory() + "/fvp-coreml-models/tag_suggester_fixture/tag_suggester_fixture.json"
        guard let raw = FileManager.default.contents(atPath: path),
              let root = (try? JSONSerialization.jsonObject(with: raw)) as? [String: Any],
              let supportRoot = root["support_root"] as? String,
              let slug = root["slug"] as? String,
              let dim = root["dim"] as? Int,
              let margin = root["suggest_margin"] as? Double,
              let maxTags = root["max_tags"] as? Int,
              let pairedNames = root["paired_names"] as? [String],
              let engineSHA = root["engine_sha256"] as? String,
              let libraryJSON = root["library_tags"] as? [[String: Any]],
              let cases = root["cases"] as? [[String: Any]] else {
            print("SKIP tag suggester — no fixture at \(path)")
            print("     build it with: /opt/anaconda3/bin/python3 docs/coreml-spike/suggest_parity.py")
            exit(0)
        }

        func f32(_ b64: String) -> [Float] {
            guard let data = Data(base64Encoded: b64) else { return [] }
            var out = [Float](repeating: 0, count: data.count / 4)
            _ = out.withUnsafeMutableBytes { data.copyBytes(to: $0) }
            return out
        }

        // MARK: the table, and the constants only engine.py may decide

        let table: PromptTable
        do { table = try PromptTable(root: supportRoot) } catch {
            print("FAIL the fixture's prompt table would not load — \(error)")
            exit(1)
        }
        checkEqual("the table is the width the fixture was built for", table.dim, dim)
        checkEqual("the table was read from the engine.py the fixture used",
                   table.engineSHA, engineSHA)
        // The margin is carried in float32, so the Swift bar is Float(0.02)
        // = 0.019999999552965164 where engine.py compares against the double
        // 0.02 — a difference of 4.5e-10, i.e. far below any margin a frame can
        // actually land on (the fixture aims 0.0205 and 0.0195 to hold this).
        checkEqual("SUGGEST_MARGIN comes from engine.py, not a copy",
                   Double(table.constants.suggestMargin), Double(Float(margin)))
        checkEqual("SUGGEST_MAX_TAGS comes from engine.py, not a copy",
                   table.constants.suggestMaxTags, maxTags)
        checkEqual("the paired tags are the fixture's PAIRED_VOCAB",
                   table.pairedTags.map(\.name).sorted(), pairedNames.sorted())
        checkEqual("the paired tags are never offered as ordinary tags",
                   table.tags.contains { pairedNames.contains($0.name) }, false)

        // MARK: the real embedding cache, read the way the app reads it

        /// The app's `EmbeddingCache.read`, including its width guard: a vector
        /// written by a different model is a miss, never a frame.
        func read(_ h: String) -> [Float]? {
            let p = (supportRoot as NSString).appendingPathComponent(
                "frames/\(slug)/\(String(h.prefix(2)))/\(h).f32")
            guard let d = FileManager.default.contents(atPath: p),
                  !d.isEmpty, d.count % 4 == 0 else { return nil }
            let n = d.count / 4
            guard n == dim else { return nil }
            var out = [Float](repeating: 0, count: n)
            _ = out.withUnsafeMutableBytes { d.copyBytes(to: $0) }
            return out
        }

        let hashes = TagPrototypes.hashes(inCache: supportRoot + "/frames", slug: slug)
        let baseline = TagPrototypes.baseline(hashes: hashes, dim: dim, read: read)
        check("the fixture's cache has frames to walk (\(hashes.count))", hashes.count > 100)
        check("the baseline comes from the whole cache, not the videos in a request",
              baseline != nil && baseline?.count == dim)

        let tagged: TagPrototypes.TaggedVideos = libraryJSON.map { t in
            (tag: t["tag"] as? String ?? "",
             videos: ((t["videos"] as? [[String: Any]]) ?? []).map { v in
                 (key: v["key"] as? String ?? "", hashes: v["hashes"] as? [String] ?? [])
             })
        }
        let prototypes = TagPrototypes.prototypes(tagged, excluding: Set(pairedNames), read: read)
        checkEqual("only the tags with 2+ analysable videos prototype",
                   prototypes.map(\.tag).sorted(), ["Bench", "Kite", "Waterfall"])

        // MARK: every case, against engine.py's own answer

        check("the fixture has cases to judge", cases.count >= 10)
        for c in cases {
            let name = c["name"] as? String ?? "?"
            let frames = (c["frames"] as? [String] ?? []).map(f32)
            let paired = c["paired"] as? Bool ?? false
            let usesLibrary = c["uses_library"] as? Bool ?? false
            let headsJSON = c["heads"] as? [[String: Any]] ?? []
            var heads = TrainedHeads(slug: slug, dim: dim)
            for h in headsJSON {
                heads.tags[h["tag"] as? String ?? ""] = LogisticHead(
                    w: f32(h["w"] as? String ?? ""),
                    b: Float(h["b"] as? Double ?? 0),
                    n: Float(h["n"] as? Double ?? 0))
            }
            let expected = (c["expected"] as? [[String: Any]] ?? []).map {
                ($0["tag"] as? String ?? "", $0["confidence"] as? Double ?? 0,
                 $0["frames"] as? Int ?? 0, $0["source"] as? String ?? "")
            }
            checkEqual("\(name): the fixture shows the engine \(frames.count) frames",
                       frames.count, c["expected_frames_seen"] as? Int ?? -1)

            let got = TagSuggester.suggest(table: table, frames: frames, heads: heads,
                                          paired: paired,
                                          prototypes: usesLibrary ? prototypes : [],
                                          baseline: usesLibrary ? baseline : nil)
            checkList("\(name): the same candidates, in the same order", got, expected)
            check("\(name): never more than the cap", got.count <= maxTags)
            if !usesLibrary {
                check("\(name): no library source without a prototype pass",
                      got.allSatisfy { $0.source != "library" })
            }
            if paired == false {
                check("\(name): a Safe video is never offered the paired tags",
                      got.allSatisfy { !pairedNames.contains($0.tag) })
            }
        }

        // MARK: the merge rules, on their own

        /// The frames of one fixture case, by name.
        func frames(of name: String) -> [[Float]] {
            guard let c = cases.first(where: { $0["name"] as? String == name }) else { return [] }
            return (c["frames"] as? [String] ?? []).map(f32)
        }
        /// A head that scores sigmoid(b) on every frame, whatever the frame is.
        func flatHead(_ b: Float) -> LogisticHead {
            LogisticHead(w: [Float](repeating: 0, count: dim), b: b, n: 0)
        }

        let clearFrames = frames(of: "clear tags, one below the bar")
        checkEqual("a head with no weight scores its bias, and 0.5 is a hit at the cut",
                   flatHead(0).hits(clearFrames), clearFrames.count)
        checkEqual("...and 0.49999 is not",
                   flatHead(-0.00002).hits(clearFrames), 0)

        // Two heads, both exactly on the cut, for two tags the prompts do NOT
        // offer: both are appended in sorted tag order, and their confidences
        // are equal — so the ranking has to be the stable one.
        let tieHeads = TrainedHeads(slug: slug, dim: dim,
                                    tags: ["Bench": flatHead(0), "Beach": flatHead(0)])
        let tie = TagSuggester.suggest(table: table, frames: clearFrames, heads: tieHeads)
        // engine.py walks `sorted(heads.keys())`, and "Beach" sorts before
        // "Bench" — the tie must keep THAT order, not the order the tags were
        // put into the dictionary (which Swift does not even preserve).
        checkEqual("a tie between two heads keeps engine.py's sorted order",
                   tie.map(\.tag), ["Beach", "Bench", "Waterfall", "Birthday"])
        let trained = tie.filter { $0.source == "trained" }
        checkEqual("both heads are on the list", trained.count, 2)
        checkEqual("two heads on the same cut share a confidence",
                   Set(trained.map(\.confidence)).count, 1)
        checkEqual("a head at 0.5 outranks the prompt pass that reached 0.35",
                   tie.map(\.tag), ["Beach", "Bench", "Waterfall", "Birthday"])
        checkEqual("...and the entries it outranked are still the prompt pass's",
                   tie.last?.source, "zeroshot")

        // The merge is not a union: an entry already on the list keeps its
        // number unless the new claim is STRICTLY stronger.
        let weak = TrainedHeads(slug: slug, dim: dim, tags: ["Waterfall": flatHead(-4)])
        let unchanged = TagSuggester.suggest(table: table, frames: clearFrames, heads: weak)
        let plain = TagSuggester.suggest(table: table, frames: clearFrames)
        checkList("a weaker head changes nothing at all", unchanged, plain.map {
            ($0.tag, $0.confidence, $0.frames, $0.source)
        })

        // A head fitted on another embedding space cannot score these frames.
        let foreign = TrainedHeads(slug: slug, dim: 8,
                                   tags: ["Bench": LogisticHead(w: [Float](repeating: 1, count: 8),
                                                               b: 0, n: 0)])
        checkList("a head of the wrong width is ignored, not mis-scored",
                  TagSuggester.suggest(table: table, frames: clearFrames, heads: foreign),
                  plain.map { ($0.tag, $0.confidence, $0.frames, $0.source) })

        // Library candidates need the baseline as well as the prototypes:
        // engine.py refuses to score margins against nothing.
        let joFrames = frames(of: "library prototypes merge into the list")
        let half = TagSuggester.suggest(table: table, frames: joFrames,
                                        prototypes: prototypes, baseline: nil)
        check("no baseline, no library candidates",
              half.allSatisfy { $0.source != "library" })

        // The zero-shot pass on its own is the ranked, capped list — the merge
        // with nothing to merge has to be exactly that.
        for c in cases where (c["paired"] as? Bool) != true {
            let fr = (c["frames"] as? [String] ?? []).map(f32)
            let merged = TagSuggester.suggest(table: table, frames: fr)
            let own = table.suggestions(vectors: fr).map {
                TagSuggester.Candidate(tag: $0.tag, confidence: LookAlikes.round4($0.confidence),
                                       frames: $0.frames, source: "zeroshot")
            }
            checkList("\(c["name"] as? String ?? "?"): the merged list starts as the ranked pass",
                      merged, own.map { ($0.tag, $0.confidence, $0.frames, $0.source) })
        }

        checkEqual("no frames, no candidates",
                   TagSuggester.suggest(table: table, frames: []).count, 0)

        // --- the optional re-ranking (FVP_SUGGEST_RANK=normalized) ------------
        //
        // Default OFF is the property that matters most: every check above ran
        // without priors and matched engine.py, so the guarantee here is that an
        // empty or too-small prior cannot change a single list.
        checkEqual("TagPriors uses the same cache namespace as the heads",
                   TagPriors.defaultSlug, TrainedHeads.defaultSlug)

        // The switch: the environment wins, then the dev override file, then
        // off. Xcode rewrites the scheme, so the file is how a session turns
        // this on — the same file that carries the engine mode.
        check("normalized via the environment",
              TagPriors.enabled(environment: "normalized", override: [:]))
        check("normalized via the override file",
              TagPriors.enabled(environment: nil, override: ["rank": "normalized"]))
        check("an empty environment falls through to the file",
              TagPriors.enabled(environment: "", override: ["rank": "normalized"]))
        check("off by default",
              !TagPriors.enabled(environment: nil, override: [:])
              && !TagPriors.enabled(environment: "off", override: ["rank": "normalized"]))
        check("anything else in the file is not a yes",
              !TagPriors.enabled(environment: nil, override: ["rank": "yes"]))

        let noPriors = TagSuggester.suggest(table: table, frames: clearFrames)
        checkList("an empty prior ranks exactly as engine.py does",
                  TagSuggester.suggest(table: table, frames: clearFrames,
                                       priors: TagPriors()),
                  noPriors.map { ($0.tag, $0.confidence, $0.frames, $0.source) })

        // A prior measured from too few frames is not trustworthy, so it must be
        // ignored rather than half-applied: a brand new library ranks as today.
        var thin = TagPriors()
        thin.frames = TagPriors.minFrames - 1
        thin.mean = Dictionary(uniqueKeysWithValues: noPriors.map { ($0.tag, 9.0) })
        checkList("a prior under the frame floor is ignored",
                  TagSuggester.suggest(table: table, frames: clearFrames, priors: thin),
                  noPriors.map { ($0.tag, $0.confidence, $0.frames, $0.source) })
        check("...and that floor is what isUsable reports", !thin.isUsable)

        // The whole point: a tag that always fires loses to one that fired
        // unusually strongly here. Penalise the leader by its own habit and it
        // must fall behind the runner-up, WITHOUT its confidence changing.
        if noPriors.count >= 2 {
            let leader = noPriors[0], runnerUp = noPriors[1]
            var priors = TagPriors()
            priors.frames = TagPriors.minFrames
            // Leader's habit is high enough to put it below the runner-up.
            priors.mean = [leader.tag: leader.confidence - runnerUp.confidence + 0.01]
            let reranked = TagSuggester.suggest(table: table, frames: clearFrames,
                                                priors: priors)
            check("a chronically-strong tag loses its lead to an unusual one",
                  reranked.first?.tag == runnerUp.tag)
            check("...and the demoted tag is still on the list",
                  reranked.contains { $0.tag == leader.tag })
            let same = reranked.first { $0.tag == leader.tag }?.confidence
            checkEqual("...carrying the SAME confidence it always had",
                       same ?? -1, leader.confidence)
            check("...so a tag with no prior keeps its raw margin",
                  priors.rankingKey(tag: "NeverSeen", confidence: 0.5) == 0.5)
        }

        // Measuring: the prior is the mean best-margin per tag over the frames
        // it is given, on the same quantity the suggester compares — so
        // measuring on ONE frame must reproduce that frame's own margins.
        let one = clearFrames[0]
        let measured = TagPriors.measure(table: table, hashes: ["h"],
                                         read: { _ in one })
        checkEqual("measuring reports how many frames it saw", measured.frames, 1)
        var exact = true
        for (tag, margin) in table.tagMargins(vector: one) {
            if abs((measured.mean[tag] ?? .nan) - Double(margin)) > 1e-12 { exact = false }
        }
        check("a one-frame prior is that frame's own margins", exact)
        check("a vector of the wrong width is skipped, not mis-measured",
              TagPriors.measure(table: table, hashes: ["h"],
                                read: { _ in [1, 2, 3] }).frames == 0)

        // --- the neighbour prior, as the suggester sees it -------------------
        //
        // The parity fixture above is ranked with NO neighbour prior, and every
        // check in this file depends on that staying true, so the no-op is
        // worth pinning here rather than trusting the default argument.
        do {
            let plain = TagSuggester.suggest(table: table, frames: clearFrames)
            let empty = TagSuggester.suggest(table: table, frames: clearFrames,
                                             neighbours: NeighbourPrior())
            check("an empty neighbour prior changes no order",
                  plain.map(\.tag) == empty.map(\.tag))

            // The ceiling: the most a perfect neighbourhood can add must stay
            // under the margin that decides whether a tag is a candidate at
            // all, so the term can only ever break a near-tie.
            check("the bonus cannot reach the vocabulary margin",
                  NeighbourPrior.weight < Double(TagSuggester.vocabularyMargin))

            // And it moves what is there rather than inventing anything: a
            // neighbourhood shouting about a tag the frames never offered must
            // not put that tag on the list.
            let loud = NeighbourPrior.measure(
                for: 1_000,
                dated: [("a", 1_010), ("b", 1_020), ("c", 1_030)],
                tagsFor: { _ in ["NoFramesEverSaidThis"] },
                excluding: "me")
            let withLoud = TagSuggester.suggest(table: table, frames: clearFrames,
                                                neighbours: loud)
            check("a tag only the neighbours know is still not offered",
                  !withLoud.contains { $0.tag == "NoFramesEverSaidThis" })
            check("...and the real candidates are all still there",
                  Set(withLoud.map(\.tag)) == Set(plain.map(\.tag)))
        }

        print(failures == 0 ? "ALL PASS tag suggester" : "\(failures) FAILURES")
        exit(failures == 0 ? 0 : 1)
    }
}
