// The library-tag prototypes, checked against engine.py's own answers.
//
// `_library_prototypes` + `_library_baseline` + `_score_library_tags` decide
// which user tags a freshly analysed video is offered. Every way of getting
// them subtly wrong still produces a plausible suggestion list: a prototype
// built from videos that were never analysed, a per-video mean normalised
// where engine.py does not normalise, a baseline that skips the videos no
// request mentions (which is *most* of the library), a margin compared with >
// instead of >=, a max taken over the hit frames instead of all of them, a
// sort that is not stable. So this replays a fixture generated by calling the
// real functions (docs/coreml-spike/prototype_parity.py) and demands
// identical output — including the numbers the UI will show.
//
// The fixture aims each target frame at a chosen margin (0.35 over the line,
// 0.25 under it) and refuses to emit itself unless every frame landed where it
// was aimed, so the hit counts below are a real test of the threshold and not
// a coincidence of the random vectors.
//
// Run: Tests/run_tag_prototypes.sh

@testable import FVPModel
import Foundation

@main
struct TagPrototypesTest {
    static func main() {
        var failures = 0
        func check(_ name: String, _ cond: Bool) {
            print(cond ? "ok   \(name)" : "FAIL \(name)")
            if !cond { failures += 1 }
        }
        func checkEqual<T: Equatable>(_ name: String, _ got: T, _ want: T) {
            let ok = got == want
            print(ok ? "ok   \(name)" : "FAIL \(name) — got \(got), want \(want)")
            if !ok { failures += 1 }
        }
        func checkClose(_ name: String, _ got: Double, _ want: Double, _ tol: Double) {
            let ok = abs(got - want) <= tol
            print(ok ? "ok   \(name)" : "FAIL \(name) — got \(got), want \(want)")
            if !ok { failures += 1 }
        }
        func checkTag(_ name: String, _ got: [TagPrototypes.Candidate],
                      _ want: [(String, Double, Int)]) {
            let flat = got.map { ($0.tag, $0.confidence, $0.frames) }
            let same = flat.count == want.count && zip(flat, want).allSatisfy {
                $0.0 == $1.0 && $0.1 == $1.1 && $0.2 == $1.2
            }
            let shown = got.map { "\($0.tag)=\($0.confidence)(\($0.frames))" }
            print(same ? "ok   \(name)" : "FAIL \(name) — got \(shown), want \(want)")
            if !same { failures += 1 }
        }

        let args = CommandLine.arguments
        let path = args.count > 1
            ? args[1]
            : NSHomeDirectory() + "/fvp-coreml-models/prototype_fixture.json"
        guard let raw = FileManager.default.contents(atPath: path),
              let root = (try? JSONSerialization.jsonObject(with: raw)) as? [String: Any],
              let dim = root["dim"] as? Int,
              let framesJSON = root["frames"] as? [String: String],
              let foreign = root["foreign_hash"] as? String,
              let cached = root["cached_hashes"] as? [String],
              let plainHashes = root["plain_hashes"] as? [String],
              let tagsJSON = root["library_tags"] as? [[String: Any]],
              let targetsJSON = root["targets"] as? [String: [String: Any]],
              let casesJSON = (root["expected"] as? [String: Any])?["cases"] as? [[String: Any]],
              let expectedProto = (root["expected"] as? [String: Any])?["prototypes"] as? [String: String],
              let expectedBase = (root["expected"] as? [String: Any])?["baseline"] as? String else {
            print("SKIP tag prototypes — no fixture at \(path)")
            print("     build it with: /opt/anaconda3/bin/python3 docs/coreml-spike/prototype_parity.py")
            exit(0)
        }

        func bytes(_ b64: String) -> Data { Data(base64Encoded: b64) ?? Data() }
        func f32(_ b64: String) -> [Float] {
            let d = bytes(b64)
            var out = [Float](repeating: 0, count: d.count / 4)
            _ = out.withUnsafeMutableBytes { d.copyBytes(to: $0) }
            return out
        }
        func f64(_ b64: String) -> [Double] {
            let d = bytes(b64)
            var out = [Double](repeating: 0, count: d.count / 8)
            _ = out.withUnsafeMutableBytes { d.copyBytes(to: $0) }
            return out
        }

        var frames: [String: [Float]] = [:]
        for (h, b) in framesJSON { frames[h] = f32(b) }
        /// The app's cache, plus one file written by a different 768-wide model.
        func read(_ h: String) -> [Float]? {
            h == foreign ? [Float](repeating: 0, count: 768) : frames[h]
        }

        // MARK: the constants, which only engine.py may decide

        checkEqual("LIBRARY_TAG_MARGIN is engine.py's",
                   TagPrototypes.margin, root["margin"] as? Double ?? -1)
        checkEqual("LIBRARY_TAG_MIN_VIDEOS is engine.py's",
                   TagPrototypes.minVideos, root["min_videos"] as? Int ?? -1)
        // The paired tags never become prototypes; the fixture names its own
        // stand-in pair, since the real one is in a private file.
        let pairedNames = Set(root["paired_names"] as? [String] ?? [])
        check("the fixture names a pair to skip", pairedNames.count == 2)

        // MARK: the prototypes

        let tagged: TagPrototypes.TaggedVideos = tagsJSON.map { t in
            (tag: t["tag"] as? String ?? "",
             videos: ((t["videos"] as? [[String: Any]]) ?? []).map { v in
                 (key: v["key"] as? String ?? "",
                  hashes: v["hashes"] as? [String] ?? [])
             })
        }
        let protos = TagPrototypes.prototypes(tagged, excluding: pairedNames, read: read)
        checkEqual("only the tags with 2+ analysable videos get a prototype",
                   protos.map(\.tag).sorted(), expectedProto.keys.sorted())
        checkEqual("a tag with one video is not a prototype", protos.contains { $0.tag == "solo" }, false)
        checkEqual("a tag whose videos were never analysed is not one either",
                   protos.contains { $0.tag == "ghost" }, false)
        checkEqual("a paired tag is skipped by name", protos.contains { pairedNames.contains($0.tag) }, false)
        for p in protos {
            let want = f64(expectedProto[p.tag] ?? "")
            checkEqual("\(p.tag) prototype is 512/768-wide like the cache", p.vector.count, dim)
            checkClose("\(p.tag) prototype is unit-normalised",
                       (p.vector.reduce(0) { $0 + $1 * $1 }).squareRoot(), 1.0, 1e-12)
            let worst = zip(p.vector, want).map { abs($0 - $1) }.max() ?? 0
            check("\(p.tag) prototype matches engine.py (max |Δ| \(worst))", worst < 1e-12)
        }

        // MARK: the baseline

        let wantBase = f64(expectedBase)
        let base = TagPrototypes.baseline(hashes: cached, dim: dim, read: read)
        let baseWorst = zip(base ?? [], wantBase).map { abs($0 - $1) }.max() ?? 1
        check("baseline matches engine.py (max |Δ| \(baseWorst))", baseWorst < 1e-12)
        checkClose("baseline is the library's average video, as a unit vector",
                   (base ?? []).reduce(0) { $0 + $1 * $1 }.squareRoot(), 1.0, 1e-12)
        check("the baseline sees the videos in NO request",
              plainHashes.allSatisfy { cached.contains($0) })
        check("a vector from another model cannot join the baseline",
              TagPrototypes.baseline(hashes: cached + [foreign], dim: dim, read: read)
                  == base)
        checkEqual("a cache with nothing usable refuses instead of averaging nothing",
                   TagPrototypes.baseline(hashes: cached, dim: dim, read: { _ in nil }) == nil, true)
        checkEqual("a cache whose vectors are the wrong width refuses too",
                   TagPrototypes.baseline(hashes: cached, dim: dim,
                                          read: { _ in [Float](repeating: 1, count: 8) }) == nil,
                   true)

        // MARK: the walk over the cache directory

        let tmp = NSTemporaryDirectory() + "fvp-tag-proto-\(getpid())/"
        let slugDir = tmp + "\(root["slug"] as? String ?? "slug")/"
        let fm = FileManager.default
        func writeF32(_ hash: String, _ vec: [Float]) {
            let dir = slugDir + String(hash.prefix(2)) + "/"
            try? fm.createDirectory(atPath: dir, withIntermediateDirectories: true)
            var data = Data(capacity: vec.count * 4)
            for f in vec {
                var le = f.bitPattern.littleEndian
                withUnsafeBytes(of: &le) { data.append(contentsOf: $0) }
            }
            fm.createFile(atPath: dir + hash + ".f32", contents: data)
        }
        // three videos, written the way the app writes them
        var walked = [String]()
        for name in ["t_hi", "t_mid", "t_none"] {
            for h in (targetsJSON[name]?["hashes"] as? [String]) ?? [] {
                writeF32(h, frames[h] ?? [])
                walked.append(h)
            }
        }
        try? fm.createDirectory(atPath: slugDir, withIntermediateDirectories: true)
        writeF32("loose", [Float](repeating: 0, count: dim))      // directly in the slug dir
        fm.createFile(atPath: slugDir + "notes.txt", contents: Data("x".utf8))
        fm.createFile(atPath: tmp + "notaslug.txt", contents: Data("x".utf8))

        func readDisk(_ h: String) -> [Float]? {
            let p = slugDir + String(h.prefix(2)) + "/" + h + ".f32"
            guard let d = fm.contents(atPath: p), !d.isEmpty, d.count % 4 == 0 else { return nil }
            var out = [Float](repeating: 0, count: d.count / 4)
            _ = out.withUnsafeMutableBytes { d.copyBytes(to: $0) }
            return out
        }
        let found = TagPrototypes.hashes(inCache: tmp, slug: root["slug"] as? String ?? "")
        checkEqual("the walk finds exactly the .f32 files in the two levels",
                   found.sorted(), (walked + ["loose"]).sorted())
        checkEqual("a file that is not .f32 is not a frame",
                   found.contains("notes"), false)
        checkEqual("a directory that is not the model slug is not searched",
                   found.contains("notaslug"), false)
        let walkedBase = TagPrototypes.baseline(hashes: found, dim: dim, read: readDisk)
        let inMemoryBase = TagPrototypes.baseline(hashes: walked, dim: dim, read: read)
        let diskWorst = zip(walkedBase ?? [], inMemoryBase ?? [])
            .map { abs($0 - $1) }.max() ?? 1
        check("reading the frames back off disk gives the same baseline (\(diskWorst))",
              diskWorst < 1e-15)
        try? fm.removeItem(atPath: tmp)

        // MARK: the suggestions

        check("the fixture has cases to judge", casesJSON.count >= 18)
        for c in casesJSON {
            let name = c["name"] as? String ?? "?"
            let video = c["video"] as? String ?? ""
            let minFrames = c["min_frames"] as? Int ?? 0
            let hashes = (targetsJSON[video]?["hashes"] as? [String]) ?? []
            let got = TagPrototypes.score(frames: hashes.map { frames[$0] ?? [] },
                                          prototypes: protos,
                                          baseline: base,
                                          minFrames: minFrames)
            let want = (c["expected"] as? [[String: Any]] ?? []).map {
                ($0["tag"] as? String ?? "", $0["confidence"] as? Double ?? 0,
                 $0["frames"] as? Int ?? 0)
            }
            checkTag("\(name): the same tags, in the same order", got, want)
            check("\(name): every hit is offered as a library tag",
                  got.allSatisfy { $0.source == "library" })
        }

        // MARK: the boundaries

        checkEqual("no prototypes, no suggestions",
                   TagPrototypes.score(frames: [[0.5, 0.0]], prototypes: [],
                                       baseline: [0.0, 0.0], minFrames: 1).count, 0)
        checkEqual("no baseline, no suggestions",
                   TagPrototypes.score(frames: [[0.5, 0.0]],
                                       prototypes: [.init(tag: "x", vector: [1.0, 0.0])],
                                       baseline: nil, minFrames: 1).count, 0)
        checkEqual("a baseline of the wrong width refuses",
                   TagPrototypes.score(frames: [[0.5, 0.0]],
                                       prototypes: [.init(tag: "x", vector: [1.0, 0.0])],
                                       baseline: [0.0, 0.0, 0.0], minFrames: 1).count, 0)
        checkEqual("no frames, no suggestions",
                   TagPrototypes.score(frames: [], prototypes: [.init(tag: "x", vector: [1.0])],
                                       baseline: [0.0], minFrames: 1).count, 0)
        checkEqual("a prototype of the wrong width is skipped, not crashed",
                   TagPrototypes.score(frames: [[0.5, 0.0]],
                                       prototypes: [.init(tag: "x", vector: [1.0, 0.0, 0.0])],
                                       baseline: [0.0, 0.0], minFrames: 1).count, 0)
        // A frame sitting exactly ON the margin counts: engine.py compares >=,
        // and 0.5 * 0.2 lands on the same double as 0.10.
        check("the comparison is >=, and 0.5 * 0.2 is exactly 0.10",
              0.5 * 0.2 >= TagPrototypes.margin)
        checkEqual("a frame exactly on the margin is a hit",
                   TagPrototypes.score(frames: [[0.2, 0.0]],
                                       prototypes: [.init(tag: "x", vector: [0.5, 0.0])],
                                       baseline: [0.0, 0.0], minFrames: 1).count, 1)
        checkEqual("a hair under the margin is not",
                   TagPrototypes.score(frames: [[0.1999, 0.0]],
                                       prototypes: [.init(tag: "x", vector: [0.5, 0.0])],
                                       baseline: [0.0, 0.0], minFrames: 1).count, 0)
        checkEqual("the frames threshold is on the count, not the best frame",
                   TagPrototypes.score(frames: [[0.9, 0.0], [0.2, 0.0]],
                                       prototypes: [.init(tag: "x", vector: [0.5, 0.0])],
                                       baseline: [0.0, 0.0], minFrames: 3).count, 0)
        // confidence is the best margin of ANY frame — including one that
        // cleared the line while another frame did not
        let two = TagPrototypes.score(frames: [[0.9, 0.0], [0.2, 0.0]],
                                      prototypes: [.init(tag: "x", vector: [0.5, 0.0])],
                                      baseline: [0.0, 0.0], minFrames: 1)
        checkTag("confidence is the best frame's margin, frames the count",
                 two, [("x", 0.45, 2)])
        let tie = TagPrototypes.score(frames: [[0.9, 0.0]],
                                      prototypes: [.init(tag: "a", vector: [0.5, 0.0]),
                                                   .init(tag: "b", vector: [0.5, 0.0])],
                                      baseline: [0.0, 0.0], minFrames: 1)
        checkTag("a tie keeps prototype order, as a stable sort would",
                 tie, [("a", 0.45, 1), ("b", 0.45, 1)])

        print(failures == 0 ? "ALL PASS tag prototypes" : "\(failures) FAILURES")
        exit(failures == 0 ? 0 : 1)
    }
}
